// <auto-generated />
using System;
using System.Net;
using Inventory_Atlas.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Inventory_Atlas.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251008064622_InitInventoryAtlas")]
    partial class InitInventoryAtlas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Audit.IpAudit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<IPAddress>("Ip")
                        .IsRequired()
                        .HasColumnType("inet")
                        .HasColumnName("ip");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("IpAudit", "Audit");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Audit.LogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Action")
                        .HasColumnType("integer")
                        .HasColumnName("action");

                    b.Property<DateTime>("ActionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("action_time");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("changes");

                    b.Property<int?>("EntityId")
                        .HasColumnType("integer")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityName")
                        .HasColumnType("text")
                        .HasColumnName("entity_name");

                    b.Property<Guid>("UserSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_session");

                    b.HasKey("Id");

                    b.HasIndex("Changes")
                        .HasDatabaseName("IX_LogEntry_Changes");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Changes"), "GIN");

                    b.HasIndex("UserSessionId");

                    b.ToTable("LogEntrys", "Audit");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Audit.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<IPAddress>("IP")
                        .HasColumnType("inet")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("UserSessions", "Audit");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Documents.CheckoutDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DocumentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("document_date");

                    b.Property<string>("DocumentName")
                        .HasColumnType("text")
                        .HasColumnName("document_number");

                    b.Property<int>("DocumentType")
                        .HasColumnType("integer")
                        .HasColumnName("document_status");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("CheckoutDocuments", "Documents");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Documents.CheckoutDocumentItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("document_id");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("ItemId");

                    b.ToTable("CheckoutDocumentItems", "Documents");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Documents.ReturnDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DocumentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("document_date");

                    b.Property<string>("DocumentName")
                        .HasColumnType("text")
                        .HasColumnName("document_number");

                    b.Property<int>("DocumentType")
                        .HasColumnType("integer")
                        .HasColumnName("document_status");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("ReturnDocuments", "Documents");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Documents.ReturnDocumentItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("document_id");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("ItemId");

                    b.ToTable("ReturnDocumentItems", "Documents");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Documents.TransferDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DocumentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("document_date");

                    b.Property<string>("DocumentName")
                        .HasColumnType("text")
                        .HasColumnName("document_number");

                    b.Property<int>("DocumentType")
                        .HasColumnType("integer")
                        .HasColumnName("document_status");

                    b.Property<int>("FromEmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("from_employee_id");

                    b.Property<int>("ToEmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("to_employee_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("FromEmployeeId");

                    b.HasIndex("ToEmployeeId");

                    b.ToTable("TransferDocuments", "Documents");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Documents.TransferDocumentItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("document_id");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("ItemId");

                    b.ToTable("TransferDocumentItems", "Documents");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Documents.WriteOffDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DocumentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("document_date");

                    b.Property<string>("DocumentName")
                        .HasColumnType("text")
                        .HasColumnName("document_number");

                    b.Property<int>("DocumentType")
                        .HasColumnType("integer")
                        .HasColumnName("document_status");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("WriteOffDocuments", "Documents");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Documents.WriteOffDocumentItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("document_id");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("items_id");

                    b.Property<int>("WriteOffItems")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("WriteOffItems");

                    b.ToTable("WriteOffDocumentItems", "Documents");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Employees.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("Departments", "Employees");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Employees.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("firstname");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsResponsible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_responsible");

                    b.Property<string>("Patronymic")
                        .HasColumnType("text")
                        .HasColumnName("patronymic");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Position")
                        .HasColumnType("text")
                        .HasColumnName("position");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("surname");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees", "Employees");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Employees.MateriallyResponsible", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("MateriallyResponsibles", "Employees");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Employees.Workplace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Workplaces", "Employees");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Inventory.FurnitureMaterialAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FurnitureId")
                        .HasColumnType("integer")
                        .HasColumnName("furniture_id");

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer")
                        .HasColumnName("material_id");

                    b.HasKey("Id");

                    b.HasIndex("FurnitureId");

                    b.ToTable("FurnitureMaterialAssignments", "Inventory");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Inventory.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<long?>("InventoryNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("inventory_number");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("RegistryId")
                        .HasColumnType("text")
                        .HasColumnName("registry_number");

                    b.Property<int?>("ResponsibleId")
                        .HasColumnType("integer")
                        .HasColumnName("responsible_id");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ResponsibleId");

                    b.ToTable("InventoryItems", "Inventory");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.References.CPU", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("Clock")
                        .HasColumnType("double precision")
                        .HasColumnName("сlock");

                    b.Property<short?>("CoreCount")
                        .HasColumnType("smallint")
                        .HasColumnName("core_count");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("text")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Socket")
                        .HasColumnType("text")
                        .HasColumnName("socket");

                    b.Property<short?>("ThreadCount")
                        .HasColumnType("smallint")
                        .HasColumnName("thread_count");

                    b.HasKey("Id");

                    b.ToTable("CPUs", "References");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.References.GPU", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short?>("DisplayPort")
                        .HasColumnType("smallint")
                        .HasColumnName("display_port");

                    b.Property<short?>("Dvi")
                        .HasColumnType("smallint")
                        .HasColumnName("dvi_port");

                    b.Property<short?>("Hdmi")
                        .HasColumnType("smallint")
                        .HasColumnName("hdmi_port");

                    b.Property<int>("MemorySize")
                        .HasColumnType("integer")
                        .HasColumnName("memory_size");

                    b.Property<int>("MemoryType")
                        .HasColumnType("integer")
                        .HasColumnName("memory_type");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Model");

                    b.Property<string>("Vendor")
                        .HasColumnType("text")
                        .HasColumnName("vendor");

                    b.Property<short?>("Vga")
                        .HasColumnType("smallint")
                        .HasColumnName("vga_port");

                    b.HasKey("Id");

                    b.ToTable("GPUs", "References");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.References.MoBo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Chipset")
                        .HasColumnType("text")
                        .HasColumnName("chipset");

                    b.Property<int>("FormFactor")
                        .HasColumnType("integer")
                        .HasColumnName("form_factor");

                    b.Property<short?>("M2Slots")
                        .HasColumnType("smallint")
                        .HasColumnName("m2_slots");

                    b.Property<short?>("MaxRamGB")
                        .HasColumnType("smallint")
                        .HasColumnName("max_ram_gb");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<short?>("PcieSlots")
                        .HasColumnType("smallint")
                        .HasColumnName("pcie_slots");

                    b.Property<short?>("RamSlots")
                        .HasColumnType("smallint")
                        .HasColumnName("ram_slots");

                    b.Property<string>("Socket")
                        .HasColumnType("text")
                        .HasColumnName("socket");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vendor");

                    b.HasKey("Id");

                    b.ToTable("MoBos", "References");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Services.FurnitureMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("FurnitureMaterials", "Services");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Services.FurnitureType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("FurnitureTypes", "Services");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Services.InventoryCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomFields")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("custom_fields");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CustomFields")
                        .HasDatabaseName("IX_InventoryCategory_CustomFields");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("CustomFields"), "GIN");

                    b.ToTable("InventoryCategorys", "Services");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Services.InventoryPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InventoryItemId")
                        .HasColumnType("integer")
                        .HasColumnName("inventory_item_id");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("photo_path");

                    b.HasKey("Id");

                    b.HasIndex("InventoryItemId");

                    b.ToTable("InventoryPhotos", "Services");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Technics.ComputerComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ComponentType")
                        .HasColumnType("integer")
                        .HasColumnName("component_type");

                    b.Property<int>("ComputerId")
                        .HasColumnType("integer")
                        .HasColumnName("computer_id");

                    b.Property<short>("Quantity")
                        .HasColumnType("smallint")
                        .HasColumnName("quantity");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text")
                        .HasColumnName("serial_number");

                    b.HasKey("Id");

                    b.HasIndex("ComputerId");

                    b.ToTable("ComputerComponents", "Technics");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Technics.MaintenanceLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<int>("DeviceId")
                        .HasColumnType("integer")
                        .HasColumnName("device_id");

                    b.Property<DateTime>("MaintenanceDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("maintenance_date");

                    b.Property<int>("MaintenanceType")
                        .HasColumnType("integer")
                        .HasColumnName("maintenance_type");

                    b.Property<int>("PerformedBy")
                        .HasColumnType("integer")
                        .HasColumnName("performed_by");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("PerformedBy");

                    b.ToTable("MaintenanceLogs", "Technics");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Technics.WorkplaceEquipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipmentId")
                        .HasColumnType("integer")
                        .HasColumnName("equipment_id");

                    b.Property<int>("WorkplaceId")
                        .HasColumnType("integer")
                        .HasColumnName("workplace_id");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("WorkplaceId");

                    b.ToTable("WorkplaceEquipment", "Technics");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Users.Favourite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId");

                    b.ToTable("Favourite", "Users");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Users.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("decription");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("PermissionJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("permissions");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PermissionJson")
                        .HasDatabaseName("IX_Role_PermissionJson");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("PermissionJson"), "GIN");

                    b.ToTable("Roles", "Users");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Users.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birth_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)")
                        .HasColumnName("phone_number");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserProfiles", "Users");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Сonsumables.PrinterCartrige", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("PrinterCartriges", "Consumables");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Inventory.Furniture", b =>
                {
                    b.HasBaseType("Inventory_Atlas.Infrastructure.Entities.Inventory.InventoryItem");

                    b.Property<string>("Dimensions")
                        .HasColumnType("text")
                        .HasColumnName("dimensions");

                    b.Property<int>("FurnitureTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<int>("Orientation")
                        .HasColumnType("integer")
                        .HasColumnName("orientation");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision")
                        .HasColumnName("weight");

                    b.HasIndex("FurnitureTypeId");

                    b.ToTable("Furnitures", "Inventory");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Inventory.GenericInventoryItem", b =>
                {
                    b.HasBaseType("Inventory_Atlas.Infrastructure.Entities.Inventory.InventoryItem");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Properties")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("properties");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Properties")
                        .HasDatabaseName("IX_GenericInventoryItem_Properties");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Properties"), "GIN");

                    b.ToTable("GenericInventoryItems", "Inventory");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Technics.Equipment", b =>
                {
                    b.HasBaseType("Inventory_Atlas.Infrastructure.Entities.Inventory.InventoryItem");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.ToTable("Equipments", "Technics");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Technics.NetworkDevice", b =>
                {
                    b.HasBaseType("Inventory_Atlas.Infrastructure.Entities.Inventory.InventoryItem");

                    b.Property<string>("AdminLogin")
                        .HasColumnType("text")
                        .HasColumnName("admin_login");

                    b.Property<string>("AdminPassword")
                        .HasColumnType("text")
                        .HasColumnName("admin_password");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<string>("Dhcp")
                        .HasColumnType("text")
                        .HasColumnName("dhcp");

                    b.Property<bool>("HasWiFi")
                        .HasColumnType("boolean")
                        .HasColumnName("has_wifi");

                    b.Property<IPAddress>("IP")
                        .HasColumnType("inet")
                        .HasColumnName("ip_address");

                    b.Property<string>("MAC")
                        .HasColumnType("text")
                        .HasColumnName("mac_address");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("NetworkBandwidth")
                        .HasColumnType("integer")
                        .HasColumnName("network_bandwidth");

                    b.Property<short?>("PortCount")
                        .HasColumnType("smallint")
                        .HasColumnName("port_count");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text")
                        .HasColumnName("serial_number");

                    b.Property<string>("WifiName")
                        .HasColumnType("text")
                        .HasColumnName("wifi_name");

                    b.Property<string>("WifiPassword")
                        .HasColumnType("text")
                        .HasColumnName("wifi_password");

                    b.ToTable("NetworkDevices", "Technics");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Technics.Components.CPUComponent", b =>
                {
                    b.HasBaseType("Inventory_Atlas.Infrastructure.Entities.Technics.ComputerComponent");

                    b.Property<int>("CPUId")
                        .HasColumnType("integer")
                        .HasColumnName("cpu_id");

                    b.HasIndex("CPUId");

                    b.ToTable("CPUComponents", "Technics");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Technics.Components.GPUComponent", b =>
                {
                    b.HasBaseType("Inventory_Atlas.Infrastructure.Entities.Technics.ComputerComponent");

                    b.Property<int>("GpuId")
                        .HasColumnType("integer")
                        .HasColumnName("gpu_id");

                    b.HasIndex("GpuId");

                    b.ToTable("GPUComponents", "Technics");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Technics.Components.MoBoComponent", b =>
                {
                    b.HasBaseType("Inventory_Atlas.Infrastructure.Entities.Technics.ComputerComponent");

                    b.Property<int>("MoBoId")
                        .HasColumnType("integer")
                        .HasColumnName("mobo_id");

                    b.HasIndex("MoBoId");

                    b.ToTable("MoBoComponents", "Technics");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Technics.Components.NetworkComponent", b =>
                {
                    b.HasBaseType("Inventory_Atlas.Infrastructure.Entities.Technics.ComputerComponent");

                    b.Property<string>("MACAddress")
                        .HasColumnType("text")
                        .HasColumnName("mac_address");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<bool>("Optical")
                        .HasColumnType("boolean")
                        .HasColumnName("optical");

                    b.Property<int?>("Speed")
                        .HasColumnType("integer")
                        .HasColumnName("speed");

                    b.ToTable("NetworkComponents", "Technics");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Technics.Components.OtherComponent", b =>
                {
                    b.HasBaseType("Inventory_Atlas.Infrastructure.Entities.Technics.ComputerComponent");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.ToTable("OtherComponents", "Technics");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Technics.Components.PSUComponent", b =>
                {
                    b.HasBaseType("Inventory_Atlas.Infrastructure.Entities.Technics.ComputerComponent");

                    b.Property<int>("Wattage")
                        .HasColumnType("integer")
                        .HasColumnName("Wattage");

                    b.ToTable("PSUComponents", "Technics");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Technics.Components.RAMComponent", b =>
                {
                    b.HasBaseType("Inventory_Atlas.Infrastructure.Entities.Technics.ComputerComponent");

                    b.Property<int>("DdrType")
                        .HasColumnType("integer")
                        .HasColumnName("ddr_type");

                    b.Property<int?>("Frequency")
                        .HasColumnType("integer")
                        .HasColumnName("frequency");

                    b.Property<short>("Size")
                        .HasColumnType("smallint")
                        .HasColumnName("size");

                    b.ToTable("RAMComponents", "Technics");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Technics.Components.SoundComponent", b =>
                {
                    b.HasBaseType("Inventory_Atlas.Infrastructure.Entities.Technics.ComputerComponent");

                    b.Property<short?>("Channels")
                        .HasColumnType("smallint")
                        .HasColumnName("channels");

                    b.Property<bool>("IsExternal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_external");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.ToTable("SoundComponents", "Technics");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Technics.Components.StorageComponent", b =>
                {
                    b.HasBaseType("Inventory_Atlas.Infrastructure.Entities.Technics.ComputerComponent");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<int>("StorageType")
                        .HasColumnType("integer")
                        .HasColumnName("storage_type");

                    b.ToTable("StorageComponents", "Technics");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Technics.Computer", b =>
                {
                    b.HasBaseType("Inventory_Atlas.Infrastructure.Entities.Technics.Equipment");

                    b.Property<IPAddress>("IP")
                        .HasColumnType("inet")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsServer")
                        .HasColumnType("boolean")
                        .HasColumnName("is_server");

                    b.Property<string>("OperatingSystem")
                        .HasColumnType("text")
                        .HasColumnName("operating_system");

                    b.ToTable("Computers", "Technics");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Technics.Laptop", b =>
                {
                    b.HasBaseType("Inventory_Atlas.Infrastructure.Entities.Technics.Equipment");

                    b.Property<double?>("Diagonal")
                        .HasColumnType("double precision")
                        .HasColumnName("diagonal");

                    b.Property<int?>("Drive")
                        .HasColumnType("integer")
                        .HasColumnName("drive");

                    b.Property<string>("GPU")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("gpu");

                    b.Property<IPAddress>("IP")
                        .HasColumnType("inet")
                        .HasColumnName("ip_address");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("model");

                    b.Property<string>("OperatingSystem")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("operating_system");

                    b.Property<string>("Processor")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("processor");

                    b.Property<int?>("RAM")
                        .HasColumnType("integer")
                        .HasColumnName("ram");

                    b.Property<string>("Resolution")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("resolution");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("serial_number");

                    b.ToTable("Laptops", "Technics");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Technics.Monitor", b =>
                {
                    b.HasBaseType("Inventory_Atlas.Infrastructure.Entities.Technics.Equipment");

                    b.Property<double?>("Diagonal")
                        .HasColumnType("double precision")
                        .HasColumnName("diagonal");

                    b.Property<short?>("DisplayPort")
                        .HasColumnType("smallint")
                        .HasColumnName("display_port");

                    b.Property<short?>("Dvi")
                        .HasColumnType("smallint")
                        .HasColumnName("dvi_port");

                    b.Property<short?>("Hdmi")
                        .HasColumnType("smallint")
                        .HasColumnName("hdmi_port");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("model");

                    b.Property<string>("PanelType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("panel_type");

                    b.Property<int?>("RefreshRate")
                        .HasColumnType("integer")
                        .HasColumnName("refresh_rate");

                    b.Property<string>("Resolution")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("resolution");

                    b.Property<short?>("Vga")
                        .HasColumnType("smallint")
                        .HasColumnName("vga_port");

                    b.ToTable("Monitors", "Technics");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Technics.Phone", b =>
                {
                    b.HasBaseType("Inventory_Atlas.Infrastructure.Entities.Technics.Equipment");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vendor");

                    b.ToTable("Phones", "Technics");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Technics.Printer", b =>
                {
                    b.HasBaseType("Inventory_Atlas.Infrastructure.Entities.Technics.Equipment");

                    b.Property<int>("CartridgeId")
                        .HasColumnType("integer")
                        .HasColumnName("cartridge_id");

                    b.Property<bool>("Color")
                        .HasColumnType("boolean")
                        .HasColumnName("color");

                    b.Property<bool>("HasScanner")
                        .HasColumnType("boolean")
                        .HasColumnName("has_scanner");

                    b.Property<IPAddress>("IP")
                        .HasColumnType("inet")
                        .HasColumnName("ip_address");

                    b.Property<string>("Model")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("model");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("serial_number");

                    b.HasIndex("CartridgeId");

                    b.ToTable("Printers", "Technics");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Technics.Scanner", b =>
                {
                    b.HasBaseType("Inventory_Atlas.Infrastructure.Entities.Technics.Equipment");

                    b.Property<bool>("Color")
                        .HasColumnType("boolean")
                        .HasColumnName("color");

                    b.Property<int?>("DPI")
                        .HasColumnType("integer")
                        .HasColumnName("dpi");

                    b.Property<IPAddress>("IP")
                        .HasColumnType("inet")
                        .HasColumnName("ip_address");

                    b.Property<string>("Model")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("model");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("serial_number");

                    b.ToTable("Scanners", "Technics");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Technics.Software", b =>
                {
                    b.HasBaseType("Inventory_Atlas.Infrastructure.Entities.Technics.Equipment");

                    b.Property<string>("LicenceKey")
                        .HasColumnType("text")
                        .HasColumnName("licence_key");

                    b.Property<string>("Vendor")
                        .HasColumnType("text")
                        .HasColumnName("vendor");

                    b.ToTable("Software", "Technics");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Technics.Tablet", b =>
                {
                    b.HasBaseType("Inventory_Atlas.Infrastructure.Entities.Technics.Equipment");

                    b.Property<float?>("Diagonal")
                        .HasColumnType("real")
                        .HasColumnName("diagonal");

                    b.Property<int?>("Drive")
                        .HasColumnType("integer")
                        .HasColumnName("drive");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<string>("OperatingSystem")
                        .HasColumnType("text")
                        .HasColumnName("operating_system");

                    b.Property<int?>("RAM")
                        .HasColumnType("integer")
                        .HasColumnName("ram");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text")
                        .HasColumnName("serial_number");

                    b.ToTable("Tablets", "Technics");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Technics.UPS", b =>
                {
                    b.HasBaseType("Inventory_Atlas.Infrastructure.Entities.Technics.Equipment");

                    b.Property<int?>("Autonomy")
                        .HasColumnType("integer")
                        .HasColumnName("autonomy_minutes");

                    b.Property<int?>("CapacityWatts")
                        .HasColumnType("integer")
                        .HasColumnName("capacity_watts");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text")
                        .HasColumnName("serial_number");

                    b.Property<short?>("SocketCount")
                        .HasColumnType("smallint")
                        .HasColumnName("socket_count");

                    b.ToTable("UPS", "Technics");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Audit.LogEntry", b =>
                {
                    b.HasOne("Inventory_Atlas.Infrastructure.Entities.Audit.UserSession", "UserSession")
                        .WithMany("LogEntries")
                        .HasForeignKey("UserSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserSession");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Documents.CheckoutDocument", b =>
                {
                    b.HasOne("Inventory_Atlas.Infrastructure.Entities.Employees.Employee", "Employee")
                        .WithMany("CheckoutDocuments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Documents.CheckoutDocumentItem", b =>
                {
                    b.HasOne("Inventory_Atlas.Infrastructure.Entities.Documents.CheckoutDocument", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inventory_Atlas.Infrastructure.Entities.Inventory.InventoryItem", "Item")
                        .WithMany("CheckoutDocumentItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Documents.ReturnDocument", b =>
                {
                    b.HasOne("Inventory_Atlas.Infrastructure.Entities.Employees.Employee", "Employee")
                        .WithMany("ReturnDocuments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Documents.ReturnDocumentItem", b =>
                {
                    b.HasOne("Inventory_Atlas.Infrastructure.Entities.Documents.ReturnDocument", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inventory_Atlas.Infrastructure.Entities.Inventory.InventoryItem", "Item")
                        .WithMany("ReturnDocumentItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Documents.TransferDocument", b =>
                {
                    b.HasOne("Inventory_Atlas.Infrastructure.Entities.Employees.Employee", "FromEmployee")
                        .WithMany("FromTransferDocuments")
                        .HasForeignKey("FromEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inventory_Atlas.Infrastructure.Entities.Employees.Employee", "ToEmployee")
                        .WithMany("ToTransferDocuments")
                        .HasForeignKey("ToEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromEmployee");

                    b.Navigation("ToEmployee");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Documents.TransferDocumentItem", b =>
                {
                    b.HasOne("Inventory_Atlas.Infrastructure.Entities.Documents.TransferDocument", "TransferDocument")
                        .WithMany("Items")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inventory_Atlas.Infrastructure.Entities.Inventory.InventoryItem", "Item")
                        .WithMany("TransferDocumentItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("TransferDocument");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Documents.WriteOffDocumentItem", b =>
                {
                    b.HasOne("Inventory_Atlas.Infrastructure.Entities.Documents.WriteOffDocument", "Document")
                        .WithMany("Items")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inventory_Atlas.Infrastructure.Entities.Inventory.InventoryItem", "Item")
                        .WithMany("WriteOffDocumentItems")
                        .HasForeignKey("WriteOffItems")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Employees.Employee", b =>
                {
                    b.HasOne("Inventory_Atlas.Infrastructure.Entities.Employees.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Employees.MateriallyResponsible", b =>
                {
                    b.HasOne("Inventory_Atlas.Infrastructure.Entities.Employees.Employee", "Employee")
                        .WithMany("MateriallyResponsibles")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Employees.Workplace", b =>
                {
                    b.HasOne("Inventory_Atlas.Infrastructure.Entities.Employees.Employee", "Employee")
                        .WithMany("Workplaces")
                        .HasForeignKey("EmployeeId");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Inventory.FurnitureMaterialAssignment", b =>
                {
                    b.HasOne("Inventory_Atlas.Infrastructure.Entities.Inventory.Furniture", "Furniture")
                        .WithMany("Materials")
                        .HasForeignKey("FurnitureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inventory_Atlas.Infrastructure.Entities.Services.FurnitureMaterial", "FurnitureMaterial")
                        .WithMany("FurnitureMaterialAssignments")
                        .HasForeignKey("FurnitureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Furniture");

                    b.Navigation("FurnitureMaterial");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Inventory.InventoryItem", b =>
                {
                    b.HasOne("Inventory_Atlas.Infrastructure.Entities.Employees.MateriallyResponsible", "Responsible")
                        .WithMany("Items")
                        .HasForeignKey("ResponsibleId");

                    b.Navigation("Responsible");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Services.InventoryPhoto", b =>
                {
                    b.HasOne("Inventory_Atlas.Infrastructure.Entities.Inventory.InventoryItem", "InventoryItem")
                        .WithMany("InventoryItemPhotos")
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryItem");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Technics.ComputerComponent", b =>
                {
                    b.HasOne("Inventory_Atlas.Infrastructure.Entities.Technics.Computer", "Computer")
                        .WithMany("ComputerComponents")
                        .HasForeignKey("ComputerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Computer");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Technics.MaintenanceLog", b =>
                {
                    b.HasOne("Inventory_Atlas.Infrastructure.Entities.Technics.Equipment", "Device")
                        .WithMany("MaintenanceLogs")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inventory_Atlas.Infrastructure.Entities.Employees.Employee", "Employee")
                        .WithMany("MaintenanceLogs")
                        .HasForeignKey("PerformedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Technics.WorkplaceEquipment", b =>
                {
                    b.HasOne("Inventory_Atlas.Infrastructure.Entities.Technics.Equipment", "Equipment")
                        .WithMany("WorkplaceEquipments")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inventory_Atlas.Infrastructure.Entities.Employees.Workplace", "Workplace")
                        .WithMany("WorkplaceEquipments")
                        .HasForeignKey("WorkplaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Workplace");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Users.Favourite", b =>
                {
                    b.HasOne("Inventory_Atlas.Infrastructure.Entities.Inventory.InventoryItem", "Item")
                        .WithMany("Favourites")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inventory_Atlas.Infrastructure.Entities.Users.UserProfile", "User")
                        .WithMany("Favourites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Users.UserProfile", b =>
                {
                    b.HasOne("Inventory_Atlas.Infrastructure.Entities.Employees.Employee", "Employee")
                        .WithMany("UserProfiles")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("Inventory_Atlas.Infrastructure.Entities.Users.Role", "Role")
                        .WithMany("UserProfiles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Inventory.Furniture", b =>
                {
                    b.HasOne("Inventory_Atlas.Infrastructure.Entities.Services.FurnitureType", "FurnitureType")
                        .WithMany("Furnitures")
                        .HasForeignKey("FurnitureTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inventory_Atlas.Infrastructure.Entities.Inventory.InventoryItem", null)
                        .WithOne()
                        .HasForeignKey("Inventory_Atlas.Infrastructure.Entities.Inventory.Furniture", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FurnitureType");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Inventory.GenericInventoryItem", b =>
                {
                    b.HasOne("Inventory_Atlas.Infrastructure.Entities.Services.InventoryCategory", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inventory_Atlas.Infrastructure.Entities.Inventory.InventoryItem", null)
                        .WithOne()
                        .HasForeignKey("Inventory_Atlas.Infrastructure.Entities.Inventory.GenericInventoryItem", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Technics.Equipment", b =>
                {
                    b.HasOne("Inventory_Atlas.Infrastructure.Entities.Inventory.InventoryItem", null)
                        .WithOne()
                        .HasForeignKey("Inventory_Atlas.Infrastructure.Entities.Technics.Equipment", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Technics.NetworkDevice", b =>
                {
                    b.HasOne("Inventory_Atlas.Infrastructure.Entities.Inventory.InventoryItem", null)
                        .WithOne()
                        .HasForeignKey("Inventory_Atlas.Infrastructure.Entities.Technics.NetworkDevice", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Technics.Components.CPUComponent", b =>
                {
                    b.HasOne("Inventory_Atlas.Infrastructure.Entities.References.CPU", "CPUReference")
                        .WithMany("CPUs")
                        .HasForeignKey("CPUId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inventory_Atlas.Infrastructure.Entities.Technics.ComputerComponent", null)
                        .WithOne()
                        .HasForeignKey("Inventory_Atlas.Infrastructure.Entities.Technics.Components.CPUComponent", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CPUReference");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Technics.Components.GPUComponent", b =>
                {
                    b.HasOne("Inventory_Atlas.Infrastructure.Entities.References.GPU", "GPUReference")
                        .WithMany("GPUs")
                        .HasForeignKey("GpuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inventory_Atlas.Infrastructure.Entities.Technics.ComputerComponent", null)
                        .WithOne()
                        .HasForeignKey("Inventory_Atlas.Infrastructure.Entities.Technics.Components.GPUComponent", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GPUReference");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Technics.Components.MoBoComponent", b =>
                {
                    b.HasOne("Inventory_Atlas.Infrastructure.Entities.Technics.ComputerComponent", null)
                        .WithOne()
                        .HasForeignKey("Inventory_Atlas.Infrastructure.Entities.Technics.Components.MoBoComponent", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inventory_Atlas.Infrastructure.Entities.References.MoBo", "MoBoReference")
                        .WithMany("MoBos")
                        .HasForeignKey("MoBoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MoBoReference");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Technics.Components.NetworkComponent", b =>
                {
                    b.HasOne("Inventory_Atlas.Infrastructure.Entities.Technics.ComputerComponent", null)
                        .WithOne()
                        .HasForeignKey("Inventory_Atlas.Infrastructure.Entities.Technics.Components.NetworkComponent", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Technics.Components.OtherComponent", b =>
                {
                    b.HasOne("Inventory_Atlas.Infrastructure.Entities.Technics.ComputerComponent", null)
                        .WithOne()
                        .HasForeignKey("Inventory_Atlas.Infrastructure.Entities.Technics.Components.OtherComponent", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Technics.Components.PSUComponent", b =>
                {
                    b.HasOne("Inventory_Atlas.Infrastructure.Entities.Technics.ComputerComponent", null)
                        .WithOne()
                        .HasForeignKey("Inventory_Atlas.Infrastructure.Entities.Technics.Components.PSUComponent", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Technics.Components.RAMComponent", b =>
                {
                    b.HasOne("Inventory_Atlas.Infrastructure.Entities.Technics.ComputerComponent", null)
                        .WithOne()
                        .HasForeignKey("Inventory_Atlas.Infrastructure.Entities.Technics.Components.RAMComponent", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Technics.Components.SoundComponent", b =>
                {
                    b.HasOne("Inventory_Atlas.Infrastructure.Entities.Technics.ComputerComponent", null)
                        .WithOne()
                        .HasForeignKey("Inventory_Atlas.Infrastructure.Entities.Technics.Components.SoundComponent", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Technics.Components.StorageComponent", b =>
                {
                    b.HasOne("Inventory_Atlas.Infrastructure.Entities.Technics.ComputerComponent", null)
                        .WithOne()
                        .HasForeignKey("Inventory_Atlas.Infrastructure.Entities.Technics.Components.StorageComponent", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Technics.Computer", b =>
                {
                    b.HasOne("Inventory_Atlas.Infrastructure.Entities.Technics.Equipment", null)
                        .WithOne()
                        .HasForeignKey("Inventory_Atlas.Infrastructure.Entities.Technics.Computer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Technics.Laptop", b =>
                {
                    b.HasOne("Inventory_Atlas.Infrastructure.Entities.Technics.Equipment", null)
                        .WithOne()
                        .HasForeignKey("Inventory_Atlas.Infrastructure.Entities.Technics.Laptop", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Technics.Monitor", b =>
                {
                    b.HasOne("Inventory_Atlas.Infrastructure.Entities.Technics.Equipment", null)
                        .WithOne()
                        .HasForeignKey("Inventory_Atlas.Infrastructure.Entities.Technics.Monitor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Technics.Phone", b =>
                {
                    b.HasOne("Inventory_Atlas.Infrastructure.Entities.Technics.Equipment", null)
                        .WithOne()
                        .HasForeignKey("Inventory_Atlas.Infrastructure.Entities.Technics.Phone", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Technics.Printer", b =>
                {
                    b.HasOne("Inventory_Atlas.Infrastructure.Entities.Сonsumables.PrinterCartrige", "Cartridge")
                        .WithMany("Printers")
                        .HasForeignKey("CartridgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inventory_Atlas.Infrastructure.Entities.Technics.Equipment", null)
                        .WithOne()
                        .HasForeignKey("Inventory_Atlas.Infrastructure.Entities.Technics.Printer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cartridge");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Technics.Scanner", b =>
                {
                    b.HasOne("Inventory_Atlas.Infrastructure.Entities.Technics.Equipment", null)
                        .WithOne()
                        .HasForeignKey("Inventory_Atlas.Infrastructure.Entities.Technics.Scanner", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Technics.Software", b =>
                {
                    b.HasOne("Inventory_Atlas.Infrastructure.Entities.Technics.Equipment", null)
                        .WithOne()
                        .HasForeignKey("Inventory_Atlas.Infrastructure.Entities.Technics.Software", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Technics.Tablet", b =>
                {
                    b.HasOne("Inventory_Atlas.Infrastructure.Entities.Technics.Equipment", null)
                        .WithOne()
                        .HasForeignKey("Inventory_Atlas.Infrastructure.Entities.Technics.Tablet", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Technics.UPS", b =>
                {
                    b.HasOne("Inventory_Atlas.Infrastructure.Entities.Technics.Equipment", null)
                        .WithOne()
                        .HasForeignKey("Inventory_Atlas.Infrastructure.Entities.Technics.UPS", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Audit.UserSession", b =>
                {
                    b.Navigation("LogEntries");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Documents.TransferDocument", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Documents.WriteOffDocument", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Employees.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Employees.Employee", b =>
                {
                    b.Navigation("CheckoutDocuments");

                    b.Navigation("FromTransferDocuments");

                    b.Navigation("MaintenanceLogs");

                    b.Navigation("MateriallyResponsibles");

                    b.Navigation("ReturnDocuments");

                    b.Navigation("ToTransferDocuments");

                    b.Navigation("UserProfiles");

                    b.Navigation("Workplaces");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Employees.MateriallyResponsible", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Employees.Workplace", b =>
                {
                    b.Navigation("WorkplaceEquipments");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Inventory.InventoryItem", b =>
                {
                    b.Navigation("CheckoutDocumentItems");

                    b.Navigation("Favourites");

                    b.Navigation("InventoryItemPhotos");

                    b.Navigation("ReturnDocumentItems");

                    b.Navigation("TransferDocumentItems");

                    b.Navigation("WriteOffDocumentItems");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.References.CPU", b =>
                {
                    b.Navigation("CPUs");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.References.GPU", b =>
                {
                    b.Navigation("GPUs");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.References.MoBo", b =>
                {
                    b.Navigation("MoBos");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Services.FurnitureMaterial", b =>
                {
                    b.Navigation("FurnitureMaterialAssignments");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Services.FurnitureType", b =>
                {
                    b.Navigation("Furnitures");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Services.InventoryCategory", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Users.Role", b =>
                {
                    b.Navigation("UserProfiles");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Users.UserProfile", b =>
                {
                    b.Navigation("Favourites");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Сonsumables.PrinterCartrige", b =>
                {
                    b.Navigation("Printers");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Inventory.Furniture", b =>
                {
                    b.Navigation("Materials");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Technics.Equipment", b =>
                {
                    b.Navigation("MaintenanceLogs");

                    b.Navigation("WorkplaceEquipments");
                });

            modelBuilder.Entity("Inventory_Atlas.Infrastructure.Entities.Technics.Computer", b =>
                {
                    b.Navigation("ComputerComponents");
                });
#pragma warning restore 612, 618
        }
    }
}
